<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FunctionLoadQueue.Function-54d4d28a-102b-4908-9d29-cffbce869ae5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.28.0" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.26.0" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.14.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunctionLoadQueue.Core\FunctionLoadQueue.Core.csproj" />
    <ProjectReference Include="..\FunctionLoadQueue.Infrastructure\FunctionLoadQueue.Infrastructure.csproj" />
  </ItemGroup>
</Project>
